

import { Project, Priority, KanbanStatus, Insumo, Composicao } from '../types';

export const mockProjects: Project[] = [
    {
        id: 'proj-1',
        nome: 'Reforma Apto 302',
        cliente: 'Família Silva',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString().split('T')[0],
        prioridade: Priority.High,
        status: KanbanStatus.InProgress,
        resumo_tecnico: 'Reforma completa de apartamento, incluindo pintura, elétrica e acabamentos.',
        initialAnalysis: 'Análise do escopo indica necessidade de demolição, construção de alvenaria, instalações elétricas e hidráulicas, além de acabamentos como pintura e instalação de piso.',
        services: [
            { id: 'serv-1', nome: 'Demolição de alvenaria', quantidade: 25, unidade: 'm²' },
            { id: 'serv-2', nome: 'Instalação de ponto elétrico', quantidade: 15, unidade: 'un' },
            { id: 'serv-3', nome: 'Pintura acrílica em paredes', quantidade: 120, unidade: 'm²' },
        ],
        doubts: [
            { id: 'dbt-1', question: 'A pintura será em superfície nova ou requer preparação (remoção de pintura antiga, correção de imperfeições)?' },
            { id: 'dbt-2', question: 'Qual o padrão de acabamento para os pontos elétricos (ex: linha Pial Plus, Tramontina Liz)?' },
            { id: 'dbt-3', question: 'A demolição inclui a remoção de entulho do local?' }
        ]
    },
    {
        id: 'proj-2',
        nome: 'Pintura Fachada Condomínio Sol',
        cliente: 'Condomínio Sol Nascente',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString().split('T')[0],
        prioridade: Priority.Medium,
        status: KanbanStatus.InProgress,
        resumo_tecnico: 'Pintura externa de 2 torres, com tratamento de fissuras e aplicação de selador.'
    },
    {
        id: 'proj-3',
        nome: 'Instalação Elétrica Loja Centro',
        cliente: 'Varejo Moderno Ltda',
        data_entrada: new Date().toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0],
        prioridade: Priority.High,
        status: KanbanStatus.Backlog,
        resumo_tecnico: 'Projeto elétrico completo para nova loja comercial, incluindo luminotécnica.'
    },
    {
        id: 'proj-4',
        nome: 'Construção Edícula Gourmet',
        cliente: 'Carlos Pereira',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString().split('T')[0],
        prioridade: Priority.Low,
        status: KanbanStatus.Backlog,
        resumo_tecnico: 'Construção de área de lazer com churrasqueira, forno a lenha e bancada.'
    },
    {
        id: 'proj-5',
        nome: 'Manutenção Telhado Galpão Industrial',
        cliente: 'Logística Total S.A.',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
        prioridade: Priority.Medium,
        status: KanbanStatus.Sent,
        resumo_tecnico: 'Reparo de vazamentos, substituição de telhas danificadas e limpeza de calhas.',
        data_envio: new Date(new Date().setDate(new Date().getDate() - 3))
    },
     {
        id: 'proj-6',
        nome: 'Consultoria de Custos',
        cliente: 'Inovatech Engenharia',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
        prioridade: Priority.Low,
        status: KanbanStatus.Approved,
        resumo_tecnico: 'Análise e otimização de planilha orçamentária para licitação pública.'
    },
    {
        id: 'proj-7',
        nome: 'Orçamento Finalizado Cobertura',
        cliente: 'Construtora Principal',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split('T')[0],
        prioridade: Priority.High,
        status: KanbanStatus.ReadyToSend,
        resumo_tecnico: 'Orçamento completo para impermeabilização de cobertura. Todos os 5 passos concluídos.'
    },
    {
        id: 'proj-8',
        nome: 'Revisão de Proposta',
        cliente: 'Startup Construtech',
        data_entrada: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString().split('T')[0],
        data_limite: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString().split('T')[0],
        prioridade: Priority.Medium,
        status: KanbanStatus.Waiting,
        resumo_tecnico: 'Aguardando feedback do cliente sobre a proposta enviada há mais de uma semana.',
        data_envio: new Date(new Date().setDate(new Date().getDate() - 15)), // Older than 14 days
        returns: [
            { id: 'ret-1', date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), notes: 'Cliente solicitou revisão dos custos de acabamento.'}
        ]
    },
];


export const mockInsumos: Insumo[] = [
    // Tabela 1: Custos de Mão de Obra
    { id: 'ins-1', nome: 'Profissional (qualquer especialidade)', unidade: 'HH', custo: 40.00, tipo: 'MaoObra' },
    { id: 'ins-2', nome: 'Ajudante (Servente)', unidade: 'HH', custo: 22.50, tipo: 'MaoObra' },
    { id: 'ins-3', nome: 'Técnico / Engenheiro para Teste', unidade: 'HH', custo: 90.00, tipo: 'MaoObra' },
    // Tabela 2: Custos de Materiais
    { id: 'ins-4', nome: 'Abraçadeira tipo "D" 3/4" com cunha', unidade: 'un', custo: 2.50, tipo: 'Material' },
    { id: 'ins-5', nome: 'Adesivo Estrutural Epóxi', unidade: 'kit (1kg)', custo: 103.50, tipo: 'Material' },
    { id: 'ins-6', nome: 'Aditivo (Bianco ou similar)', unidade: 'L', custo: 25.50, tipo: 'Material' },
    { id: 'ins-7', nome: 'Aditivo para Argamassa CCA', unidade: 'L', custo: 23.75, tipo: 'Material' },
    { id: 'ins-8', nome: 'Álcool Isopropílico', unidade: 'frasco (1L)', custo: 31.50, tipo: 'Material' },
    { id: 'ins-9', nome: 'Arco de Serra Manual 12"', unidade: 'un', custo: 25.00, tipo: 'Material' },
    { id: 'ins-10', nome: 'Argamassa Colante AC-II', unidade: 'kg', custo: 1.30, tipo: 'Material' },
    { id: 'ins-11', nome: 'Argamassa Colante ACIII', unidade: 'kg', custo: 1.90, tipo: 'Material' },
    { id: 'ins-12', nome: 'Argamassa Pronta Matrix 4201 Contrapiso', unidade: 'saco (40kg)', custo: 28.00, tipo: 'Material' },
    { id: 'ins-13', nome: 'Areia Fina', unidade: 'saco (20kg)', custo: 6.00, tipo: 'Material' },
    { id: 'ins-14', nome: 'Areia Média', unidade: 'saco (20kg)', custo: 5.50, tipo: 'Material' },
    { id: 'ins-15', nome: 'Asfalto a Frio', unidade: 'saco (25kg)', custo: 62.00, tipo: 'Material' },
    { id: 'ins-16', nome: 'Bandeja para pintura pequena', unidade: 'un', custo: 6.00, tipo: 'Material' },
    { id: 'ins-17', nome: 'BGS (Brita Graduada Simples)', unidade: 'm³', custo: 143.33, tipo: 'Material' },
    { id: 'ins-18', nome: 'Bloco Cerâmico 14x19x29cm', unidade: 'un', custo: 2.73, tipo: 'Material' },
    { id: 'ins-19', nome: 'Bloco de Concreto 14x19x39cm', unidade: 'un', custo: 4.55, tipo: 'Material' },
    { id: 'ins-20', nome: 'Bloco de Concreto 19x19x39cm', unidade: 'un', custo: 4.73, tipo: 'Material' },
    { id: 'ins-21', nome: 'Bloco de Concreto Celular (CCA) 60x30x10cm', unidade: 'un', custo: 26.33, tipo: 'Material' },
    { id: 'ins-22', nome: 'Brita 1', unidade: 'saco (20kg)', custo: 6.50, tipo: 'Material' },
    { id: 'ins-23', nome: 'Cabos Elétricos 2,5mm² (Flexível, F+N+T)', unidade: 'm', custo: 6.83, tipo: 'Material' },
    { id: 'ins-24', nome: 'Cimento (50 kg)', unidade: 'saco', custo: 33.87, tipo: 'Material' },
    { id: 'ins-25', nome: 'Conector para Sealtube 3/4"', unidade: 'un', custo: 5.50, tipo: 'Material' },
    { id: 'ins-26', nome: 'Disco Diamantado 4.1/2"', unidade: 'un', custo: 35.00, tipo: 'Material' },
    { id: 'ins-27', nome: 'Disco de Corte Fino (para metal, 4.1/2")', unidade: 'un', custo: 8.00, tipo: 'Material' },
    { id: 'ins-28', nome: 'Dispenser de Acrílico', unidade: 'un', custo: 47.67, tipo: 'Material' },
    { id: 'ins-29', nome: 'Disjuntor Termomagnético 20A (Monopolar)', unidade: 'un', custo: 18.33, tipo: 'Material' },
    { id: 'ins-30', nome: 'Eletroduto Aço Inox 3/4"', unidade: 'm', custo: 48.33, tipo: 'Material' },
    { id: 'ins-31', nome: 'Emulsão Asfáltica (imprimação)', unidade: 'balde (18L)', custo: 173.33, tipo: 'Material' },
    { id: 'ins-32', nome: 'EPS com Isolamento Térmico T1F (100mm)', unidade: 'm²', custo: 39.00, tipo: 'Material' },
    { id: 'ins-33', nome: 'EPS 15cm', unidade: 'm²', custo: 59.00, tipo: 'Material' },
    { id: 'ins-34', nome: 'EPS Reciclado (90mm)', unidade: 'm²', custo: 21.50, tipo: 'Material' },
    { id: 'ins-35', nome: 'EPS Reciclado (100mm)', unidade: 'm²', custo: 24.00, tipo: 'Material' },
    { id: 'ins-36', nome: 'Fita Adesiva Larga (Silver Tape)', unidade: 'rolo', custo: 24.33, tipo: 'Material' },
    { id: 'ins-37', nome: 'Fita crepe 18mm x 50m', unidade: 'rolo', custo: 7.50, tipo: 'Material' },
    { id: 'ins-38', nome: 'Fita Dupla Face Alta Aderência (VHB)', unidade: 'ml', custo: 16.50, tipo: 'Material' },
    { id: 'ins-39', nome: 'Fita de Papel para Juntas Drywall', unidade: 'rolo (150m)', custo: 20.33, tipo: 'Material' },
    { id: 'ins-40', nome: 'Fita Isolante', unidade: 'rolo', custo: 11.00, tipo: 'Material' },
    { id: 'ins-41', nome: 'Fundo Epóxi', unidade: 'galão (3,6L)', custo: 260.00, tipo: 'Material' },
    { id: 'ins-42', nome: 'Gás GLP (Botijão P13)', unidade: 'un', custo: 115.00, tipo: 'Material' },
    { id: 'ins-43', nome: 'Guia / Montante Aço Galvanizado 70mm', unidade: 'barra (3m)', custo: 45.00, tipo: 'Material' },
    { id: 'ins-44', nome: 'Impermeabilizante (Viaplus 7000)', unidade: 'cx (18kg)', custo: 191.67, tipo: 'Material' },
    { id: 'ins-45', nome: 'Lâmina de Serra Sabre (para madeira)', unidade: 'un', custo: 21.50, tipo: 'Material' },
    { id: 'ins-46', nome: 'Lâmina de Serra Sabre (para metal)', unidade: 'un', custo: 23.50, tipo: 'Material' },
    { id: 'ins-47', nome: 'Lixa para massa grão 150', unidade: 'folha', custo: 1.80, tipo: 'Material' },
    { id: 'ins-48', nome: 'Lona Plástica para Proteção (fina)', unidade: 'm²', custo: 2.00, tipo: 'Material' },
    { id: 'ins-49', nome: 'Lona Plástica Transparente (Rolo 4x25m)', unidade: 'un', custo: 95.00, tipo: 'Material' },
    { id: 'ins-50', nome: 'Lona Plástica 200 Micra', unidade: 'm²', custo: 4.17, tipo: 'Material' },
    { id: 'ins-51', nome: 'Massa para Juntas Drywall', unidade: 'balde (15kg)', custo: 93.33, tipo: 'Material' },
    { id: 'ins-52', nome: 'Massa Premium Santa Luzia', unidade: 'pote', custo: 26.50, tipo: 'Material' },
    { id: 'ins-53', nome: 'Manta Asfáltica 4mm (Tipo II)', unidade: 'm²', custo: 35.67, tipo: 'Material' },
    { id: 'ins-54', nome: 'Manta Asfáltica Autoadesiva', unidade: 'm²', custo: 48.33, tipo: 'Material' },
    { id: 'ins-55', nome: 'Membrana de Poliuretano (PU)', unidade: 'kg', custo: 65.00, tipo: 'Material' },
    { id: 'ins-56', nome: 'Painel Lã de Rocha (144 kg/m³)', unidade: 'm²', custo: 130.00, tipo: 'Material' },
    { id: 'ins-57', nome: 'Papel Kraft ou Filme PE', unidade: 'm²', custo: 1.83, tipo: 'Material' },
    { id: 'ins-58', nome: 'Parafuso com bucha S6', unidade: 'kit (c/ 10)', custo: 4.50, tipo: 'Material' },
    { id: 'ins-59', nome: 'Parafusos e buchas para fixação (kit S8)', unidade: 'cj', custo: 11.00, tipo: 'Material' },
    { id: 'ins-60', nome: 'Parafusos para Drywall (T.A. e T.L.)', unidade: 'caixa', custo: 33.33, tipo: 'Material' },
    { id: 'ins-61', nome: 'Perfil e Acessórios para Fire Stop', unidade: 'ml', custo: 30.00, tipo: 'Material' },
    { id: 'ins-62', nome: 'Perfil de Junta Plástico', unidade: 'ml', custo: 8.67, tipo: 'Material' },
    { id: 'ins-63', nome: 'Placa de Gesso Acartonado RU', unidade: 'un', custo: 42.67, tipo: 'Material' },
    { id: 'ins-64', nome: 'Primer Asfáltico', unidade: 'L', custo: 20.67, tipo: 'Material' },
    { id: 'ins-65', nome: 'Primer Epóxi', unidade: 'kg', custo: 76.67, tipo: 'Material' },
    { id: 'ins-66', nome: 'Raspador manual de rejunte', unidade: 'un', custo: 19.67, tipo: 'Material' },
    { id: 'ins-67', nome: 'Revestimento cerâmico (genérico)', unidade: 'pç', custo: 14.50, tipo: 'Material' },
    { id: 'ins-68', nome: 'Rodapé Poliestireno S. Luzia', unidade: 'ml', custo: 37.00, tipo: 'Material' },
    { id: 'ins-69', nome: 'Rolo de lã para epóxi 9cm', unidade: 'un', custo: 12.00, tipo: 'Material' },
    { id: 'ins-70', nome: 'Saco de ráfia', unidade: 'un', custo: 2.50, tipo: 'Material' },
    { id: 'ins-71', nome: 'Sealtubo Metálico 3/4"', unidade: 'm', custo: 11.33, tipo: 'Material' },
    { id: 'ins-72', nome: 'Selante PU', unidade: 'tubo (300ml)', custo: 32.33, tipo: 'Material' },
    { id: 'ins-73', nome: 'Super Adesivo Santa Luzia', unidade: 'tubo', custo: 48.00, tipo: 'Material' },
    { id: 'ins-74', nome: 'Tábua de Pinus Bruta (fôrma)', unidade: 'm²', custo: 43.33, tipo: 'Material' },
    { id: 'ins-75', nome: 'Tampão PVC p/ Água (1/2")', unidade: 'un', custo: 2.40, tipo: 'Material' },
    { id: 'ins-76', nome: 'Tampão PVC p/ Água (3/4" ou 1")', unidade: 'un', custo: 3.50, tipo: 'Material' },
    { id: 'ins-77', nome: 'Tampão PVC p/ Esgoto (DN 40mm)', unidade: 'un', custo: 2.40, tipo: 'Material' },
    { id: 'ins-78', nome: 'Tampão PVC p/ Esgoto (DN 50mm)', unidade: 'un', custo: 4.50, tipo: 'Material' },
    { id: 'ins-79', nome: 'Tampão PVC p/ Esgoto (DN 100mm)', unidade: 'un', custo: 7.20, tipo: 'Material' },
    { id: 'ins-80', nome: 'Tela de Poliéster para Impermeabilização', unidade: 'm²', custo: 7.33, tipo: 'Material' },
    { id: 'ins-81', nome: 'Tela hexagonal tipo "galinheiro"', unidade: 'm²', custo: 6.00, tipo: 'Material' },
    { id: 'ins-82', nome: 'Tela Soldada Q61', unidade: 'painel', custo: 88.33, tipo: 'Material' },
    { id: 'ins-83', nome: 'Tela Soldada Q92', unidade: 'm²', custo: 25.00, tipo: 'Material' },
    { id: 'ins-84', nome: 'Tinta Intumescente', unidade: 'L', custo: 180.00, tipo: 'Material' },
    { id: 'ins-85', nome: 'Tinta Epóxi', unidade: 'galão (3,6L)', custo: 310.00, tipo: 'Material' },
    { id: 'ins-86', nome: 'Tomada Industrial 2P+T (16A)', unidade: 'un', custo: 45.00, tipo: 'Material' },
    { id: 'ins-87', nome: 'Trincha 1"', unidade: 'un', custo: 5.00, tipo: 'Material' },
    { id: 'ins-88', nome: 'Tubo PPR 25mm', unidade: 'm', custo: 12.00, tipo: 'Material' },
    { id: 'ins-89', nome: 'Tubo PVC Esgoto 40mm', unidade: 'm', custo: 8.00, tipo: 'Material' },
    { id: 'ins-90', nome: 'Vergalhão CA-50 10mm (3/8")', unidade: 'kg', custo: 9.00, tipo: 'Material' },
    // Tabela 3: Custos de Equipamentos e Serviços
    { id: 'ins-91', nome: 'Carrinho de Carga Plataforma 300kg', unidade: 'diária', custo: 40.00, tipo: 'Equipamento' },
    { id: 'ins-92', nome: 'Locação Caminhão Munck', unidade: 'hora', custo: 266.67, tipo: 'Equipamento' },
    { id: 'ins-93', nome: 'Locação de Betoneira 400L', unidade: 'diária', custo: 120.00, tipo: 'Equipamento' },
    { id: 'ins-94', nome: 'Locação de Chapa de Aço 1/2"', unidade: 'diária', custo: 45.00, tipo: 'Equipamento' },
    { id: 'ins-95', nome: 'Locação de Esmerilhadeira', unidade: 'diária', custo: 56.67, tipo: 'Equipamento' },
    { id: 'ins-96', nome: 'Locação de Martelete (30kg)', unidade: 'diária', custo: 181.67, tipo: 'Equipamento' },
    { id: 'ins-97', nome: 'Locação de Martelete Leve', unidade: 'diária', custo: 96.67, tipo: 'Equipamento' },
    { id: 'ins-98', nome: 'Locação de Martelete Médio (10-15kg)', unidade: 'diária', custo: 136.67, tipo: 'Equipamento' },
    { id: 'ins-99', nome: 'Locação de Martelete Pequeno', unidade: 'diária', custo: 76.67, tipo: 'Equipamento' },
    { id: 'ins-100', nome: 'Locação de Parafusadeira/Desparafusadeira', unidade: 'diária', custo: 50.00, tipo: 'Equipamento' },
    { id: 'ins-101', nome: 'Locação de Placa Vibratória ("Sapo")', unidade: 'diária', custo: 110.00, tipo: 'Equipamento' },
    { id: 'ins-102', nome: 'Locação de Rompedor Pesado (>25kg)', unidade: 'diária', custo: 228.33, tipo: 'Equipamento' },
    { id: 'ins-103', nome: 'Locação de Rolo Compactador Liso (Manual)', unidade: 'diária', custo: 250.00, tipo: 'Equipamento' },
    { id: 'ins-104', nome: 'Locação de Serra Clipper', unidade: 'diária', custo: 136.67, tipo: 'Equipamento' },
    { id: 'ins-105', nome: 'Locação de Termofusora para PPR', unidade: 'diária', custo: 96.67, tipo: 'Equipamento' },
    { id: 'ins-106', nome: 'Locação de Vibrador de Imersão', unidade: 'diária', custo: 77.50, tipo: 'Equipamento' },
    { id: 'ins-107', nome: 'Plataforma de Andaime Tubular', unidade: 'diária', custo: 70.00, tipo: 'Equipamento' },
    { id: 'ins-108', nome: 'Remoção de Entulho (Bota-Fora)', unidade: 'm³', custo: 90.00, tipo: 'Equipamento' },
    { id: 'ins-109', nome: 'Ventosas de Sucção para Vidro (par)', unidade: 'diária', custo: 80.00, tipo: 'Equipamento' },
];

export const mockComposicoes: Composicao[] = [];